//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public Goods()
        {
            this.Capacity = new HashSet<Capacity>();
            this.Danage = new HashSet<Danage>();
            this.EnterWarehouse = new HashSet<EnterWarehouse>();
            this.IssueWarehouse = new HashSet<IssueWarehouse>();
            this.mobilize = new HashSet<mobilize>();
        }
    
        public int Gdid { get; set; }
        public string Gdname { get; set; }
        public int Gid { get; set; }
        public string Gunit { get; set; }
        public string Gpt { get; set; }
        public int Sid { get; set; }
        public decimal Gpl { get; set; }
        public decimal Grp { get; set; }
        public string Gremarks { get; set; }
    
        public virtual ICollection<Capacity> Capacity { get; set; }
        public virtual ICollection<Danage> Danage { get; set; }
        public virtual ICollection<EnterWarehouse> EnterWarehouse { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<IssueWarehouse> IssueWarehouse { get; set; }
        public virtual ICollection<mobilize> mobilize { get; set; }
    }
}
