//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueWarehouse
    {
        public IssueWarehouse()
        {
            this.Retruerequest = new HashSet<Retruerequest>();
        }
    
        public int Iwid { get; set; }
        public int Cid { get; set; }
        public System.DateTime Iwdate { get; set; }
        public decimal Iwamount { get; set; }
        public int Stid { get; set; }
        public string Iwremarks { get; set; }
        public int Gdid { get; set; }
        public int Icount { get; set; }
        public int Estate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Goods Goods { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual ICollection<Retruerequest> Retruerequest { get; set; }
    }
}
