//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retruerequest
    {
        public int Rid { get; set; }
        public decimal Rmoney { get; set; }
        public string Rreason { get; set; }
        public int Stid { get; set; }
        public string Rremarks { get; set; }
        public int Rstate { get; set; }
        public int Iwid { get; set; }
    
        public virtual IssueWarehouse IssueWarehouse { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
