//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.Danage = new HashSet<Danage>();
            this.Enterrequest = new HashSet<Enterrequest>();
            this.EnterWarehouse = new HashSet<EnterWarehouse>();
            this.IssueWarehouse = new HashSet<IssueWarehouse>();
            this.Retruerequest = new HashSet<Retruerequest>();
            this.WareHouse = new HashSet<WareHouse>();
        }
    
        public int Stid { get; set; }
        public string Stname { get; set; }
        public string Stsex { get; set; }
        public int Stage { get; set; }
        public decimal Stwayes { get; set; }
        public string Sttelep { get; set; }
    
        public virtual ICollection<Danage> Danage { get; set; }
        public virtual ICollection<Enterrequest> Enterrequest { get; set; }
        public virtual ICollection<EnterWarehouse> EnterWarehouse { get; set; }
        public virtual ICollection<IssueWarehouse> IssueWarehouse { get; set; }
        public virtual ICollection<Retruerequest> Retruerequest { get; set; }
        public virtual ICollection<WareHouse> WareHouse { get; set; }
    }
}
