//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareHouse
    {
        public WareHouse()
        {
            this.Capacity = new HashSet<Capacity>();
            this.mobilize = new HashSet<mobilize>();
            this.mobilize1 = new HashSet<mobilize>();
        }
    
        public int Wid { get; set; }
        public string Wname { get; set; }
        public int Stid { get; set; }
        public string Waddress { get; set; }
        public string Wtelep { get; set; }
        public int Wcapacity { get; set; }
    
        public virtual ICollection<Capacity> Capacity { get; set; }
        public virtual ICollection<mobilize> mobilize { get; set; }
        public virtual ICollection<mobilize> mobilize1 { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
